### ISSUE TITLE
Find and attach xlsx file which represents calls to sponsors and partners.

### ISSUE THREAD

**Issue by alenhrga** [KaidanAlenko/frms-data-populator#1]
Find and attach xlsx file in comment section which represents calls to sponsors and partners.

After that, export that file to CSV (seperated by `,` symbol) and attach it to another comment.

**Comment by blondviper** [comment]
package hr.eestec_zg.java;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.OpenOption;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.function.Consumer;
import java.util.stream.Stream;

public class Main {

    public static void main(String[] args) throws IOException {

        Path filePath = Paths.get("C:\\Users\\Pia\\IdeaProjects\\JavaApp\\etc\\ulazni_podaci.csv");
        BufferedWriter writer = Files.newBufferedWriter(
                Paths.get("C:\\Users\\Pia\\Desktop\\izlaz.csv"), StandardCharsets.UTF_8);
        try {
            Stream<String> lineStream = Files.lines(filePath, StandardCharsets.UTF_8);
            lineStream
                    .skip(1)
                    .forEach(line -> {
                        try {
                            obradiLiniju(line, writer);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    });
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Dogodio se exception: " + e.getMessage());
            System.exit(-1);
        }
        System.out.println("Done");
    }

    private static void obradiLiniju(String line, BufferedWriter writer) throws IOException {
        String[] tokens= line.split(",");

        for (String element : tokens) {
            System.out.println(element);
            writer.write(element + System.lineSeparator());
        }
    }

}

**Comment by blondviper** [comment]
[izlaz.txt](https://github.com/KaidanAlenko/frms-data-populator/files/1056460/izlaz.txt)
Ovako izgleda izlaz i u csv file-u no pošto ga ne mogu tu upload-ati i neće mi zipani file prihvatiti onda sam ti ovako poslala. Pa sad mi reci jesam li dobro rješila svoj zadatak ili ne? :)

**Comment by alenhrga** [comment]
Izgleda mi dobro. Oćeš mi poslat molim te Java datoteku, ne da mi se
kopirat ovaj tekst iz maila?
Ispis je dobar :)

**Comment by alenhrga** [comment]
Izgleda mi dobro. Oćeš mi poslat molim te Java datoteku, ne da mi se kopirat ovaj tekst iz maila?
Ispis je dobar :)

**Comment by blondviper** [comment]
Evo izvoli, oprosti stvarno bila sam na poslu cijelo popodne.

2017-06-07 13:45 GMT+02:00 Alen <notifications@github.com>:

**Comment by alenhrga** [comment]
Ma sve okej ;)

**Comment by alenhrga** [comment]
Zadatak riješen :)
Kad stignem, objasnit ću ti zašto nam to treba, i pokazati kako to ukomponirati u naš sustav.
